In [2]:
import pandas as pd
import numpy as np
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
matplotlib.rc('font', family = 'Malgun Gothic')
matplotlib.rc('axes', unicode_minus=False)
warnings.filterwarnings('ignore')
import matplotlib.ticker as ticker

In [6]:
df = pd.read_csv('data_total.csv')
df

,Unnamed: 0,회원번호,회원상태,구매수량,구매금액,주문일시,배송시작일,배송완료일,사용 적립금,사용 포인트 네이버,...,주소지,세부주소지,나이대,물품명,물품대분류,물품중분류,상품중량,제품군,가격대,관심물품중분류
0,0,1032097472,정상회원,1.0,7083,2022-01-08,NaN,NaN,0,0,...,경기도,화성시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
1,1,1032097472,정상회원,1.0,10338,2022-09-16,2022-09-17,2022-09-18,0,0,...,경기도,화성시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
2,2,1032097472,정상회원,1.0,10338,2022-06-18,2022-06-18,2022-06-18,0,0,...,경기도,화성시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
3,3,1032097472,정상회원,1.0,10338,2022-04-02,2022-04-02,2022-04-02,0,0,...,경기도,화성시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
4,4,1032097472,정상회원,1.0,8615,2022-05-07,2022-05-07,2022-05-08,0,0,...,경기도,화성시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422231,422231,975691776,정상회원,3.0,149324,2022-02-20,2022-02-22,2022-02-23,0,0,...,광주광역시,동구,30대,개복숭아감식초모음,음료,음료기타,NaN,음료/주류,저가,라면
422232,422232,442656000,정상회원,1.0,260360,2022-02-11,2022-02-13,2022-02-15,5210,0,...,인천광역시,남동구,50대,한우등심선물,소,한우,2kg,정육/계란,저가,당근
422233,422233,322448448,정상회원,1.0,260360,2022-02-18,2022-02-19,2022-02-20,0,0,...,경기도,이천시,30대,한우등심선물,소,한우,2kg,정육/계란,저가,한우
422234,422234,204041216,정상회원,1.0,7083,2022-01-16,2022-01-16,2022-01-16,0,0,...,경기도,화성시,40대,당근토마토즙,음료,과즙,620ml,음료/주류,고가,논지엠오유정란
422235,422235,1219033792,정상회원,1.0,7083,2022-01-13,NaN,NaN,0,0,...,경상북도,구미시,20대,당근토마토즙,음료,과즙,620ml,음료/주류,고가,논지엠오유정란

In [9]:
# 주문 취소 행 삭제
df = df[df['주문취소여부'] != '주문취소']

In [11]:
df_10 = df[df['주문월'] == 10]

In [13]:
df_10

,Unnamed: 0,회원번호,회원상태,구매수량,구매금액,주문일시,배송시작일,배송완료일,사용 적립금,사용 포인트 네이버,...,주소지,세부주소지,나이대,물품명,물품대분류,물품중분류,상품중량,제품군,가격대,관심물품중분류
9,9,369152832,정상회원,1.0,10338,2022-10-26,2022-10-26,2022-10-26,0,0,...,울산광역시,남구,40대,유정란/친환경,알,논지엠오유정란,10알,알,고가,보리살림(냉장)
23,23,438814080,정상회원,1.0,10338,2022-10-05,2022-10-05,2022-10-05,0,0,...,세종특별자치시,조치원읍,60대,유정란/친환경,알,논지엠오유정란,10알,알,고가,단과자빵
33,33,869925760,정상회원,1.0,10338,2022-10-16,2022-10-16,2022-10-17,0,0,...,서울특별시,마포구,40대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
46,46,869925760,정상회원,1.0,10338,2022-10-19,2022-10-19,2022-10-19,0,0,...,서울특별시,마포구,40대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
54,54,609753536,정상회원,1.0,13401,2022-10-25,2022-10-27,2022-10-28,5240,0,...,충청남도,아산시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,"식빵, 식사대용"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422159,422159,1364147008,정상회원,1.0,11295,2022-10-19,2022-10-19,2022-10-21,0,0,...,부산광역시,남구,20대,곱게다진오징어,냉동수산,기타냉동수산,80g,수산물/건해산,고가,아이스크림
422160,422160,1640791232,정상회원,1.0,11295,2022-10-30,2022-11-01,2022-11-02,0,0,...,전라남도,고흥군,20대,곱게다진오징어,냉동수산,기타냉동수산,80g,수산물/건해산,고가,기타냉동수산
422164,422164,1028092224,정상회원,1.0,67962,2022-10-06,2022-10-06,2022-10-08,0,0,...,부산광역시,강서구,30대,한우구이용갈비,소,한우,800g,정육/계란,저가,무항생제닭
422172,422172,1027992000,정상회원,1.0,74662,2022-10-09,2022-10-09,2022-10-10,0,0,...,인천광역시,중구,50대,떠먹는배도라지청모음,건강일반,추출/농축액,230g*2병,건강식품,저가,미역/다시마
422184,422184,372553024,정상회원,1.0,74662,2022-10-03,2022-10-03,2022-10-03,0,2440,...,부산광역시,사하구,30대,떠먹는배도라지청모음,건강일반,추출/농축액,230g*2병,건강식품,저가,두부

In [36]:
df_total = pd.read_csv('data_total.csv')
df_total.head()

,Unnamed: 0,회원번호,회원상태,구매수량,구매금액,주문일시,배송시작일,배송완료일,사용 적립금,사용 포인트 네이버,...,주소지,세부주소지,나이대,물품명,물품대분류,물품중분류,상품중량,제품군,가격대,관심물품중분류
0,0,1032097472,정상회원,1.0,7083,2022-01-08,NaN,NaN,0,0,...,경기도,화성시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
1,1,1032097472,정상회원,1.0,10338,2022-09-16,2022-09-17,2022-09-18,0,0,...,경기도,화성시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
2,2,1032097472,정상회원,1.0,10338,2022-06-18,2022-06-18,2022-06-18,0,0,...,경기도,화성시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
3,3,1032097472,정상회원,1.0,10338,2022-04-02,2022-04-02,2022-04-02,0,0,...,경기도,화성시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부
4,4,1032097472,정상회원,1.0,8615,2022-05-07,2022-05-07,2022-05-08,0,0,...,경기도,화성시,30대,유정란/친환경,알,논지엠오유정란,10알,알,고가,두부

In [ ]:
# 주문월에 10이 있는지 여부에 따라 점수 부여 함수 정의
def assign_score(group):
    if 10 in group['주문월'].values:
        return 3
    else:
        return 0

# 회원번호별로 그룹화하여 점수 부여
df['점수'] = df.groupby('회원번호').apply(assign_score).reset_index(drop=True)

# 결과 출력
print(df)